name: "TrailSync"
description: "Offline coords and compass"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  baseflow_plugin_template: ^2.2.0
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  provider: ^6.1.2
  shared_preferences: ^2.4.0
  rename_app: ^1.6.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/

flutter_icons:
  android: true
  image_path: "assets/images/app_icon2.jpeg"